controllers:
    resource: ../src/Controller/
    type: attribute

auth:
    path: /auth
    methods: [POST]
    
app_product_index:
    path: /produits
    controller: App\Controller\ProductController::index
